version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: verifyme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - verifyme-network

  gov-provider:
    build: ../app/gov-provider
    container_name: gov-provider
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=${MONGO_URI_GOV}
    depends_on:
      - mongo
    networks:
      - verifyme-network

  verification-gateway:
    build: ../app/verification-gateway
    container_name: verification-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI_GATEWAY}
      - GOV_PROVIDER_URL=${GOV_PROVIDER_URL}
      - GOV_CLIENT_ID=${GOV_CLIENT_ID}
      - GOV_CLIENT_SECRET=${GOV_CLIENT_SECRET}
    depends_on:
      - mongo
      - gov-provider
    networks:
      - verifyme-network

networks:
  verifyme-network:
    driver: bridge

volumes:
  mongo-data: