version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: verifyme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - verifyme-network

  gov-postgres:
    image: postgres:15-alpine
    container_name: gov-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gov_billing
    volumes:
      - gov-postgres-data:/var/lib/postgresql/data
    networks:
      - verifyme-network

  gov-redis:
    image: redis:7-alpine
    container_name: gov-redis
    ports:
      - "6379:6379"
    networks:
      - verifyme-network

  gov-provider:
    build: ../app/gov-provider
    container_name: gov-provider
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=${MONGO_URI_GOV}
      - POSTGRES_URI=postgres://postgres:postgres@gov-postgres:5432/gov_billing
      - REDIS_URL=redis://gov-redis:6379
    depends_on:
      - mongo
      - gov-postgres
      - gov-redis
    networks:
      - verifyme-network

  gateway-postgres:
    image: postgres:15-alpine
    container_name: gateway-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gateway_billing
    volumes:
      - gateway-postgres-data:/var/lib/postgresql/data
    networks:
      - verifyme-network

  gateway-redis:
    image: redis:7-alpine
    container_name: gateway-redis
    ports:
      - "6380:6379"
    networks:
      - verifyme-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: verifyme-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - verifyme-network

  verification-gateway:
    build: ../app/verification-gateway
    container_name: verification-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI_GATEWAY}
      - GOV_PROVIDER_URL=${GOV_PROVIDER_URL}
      - GOV_CLIENT_ID=${GOV_CLIENT_ID}
      - GOV_CLIENT_SECRET=${GOV_CLIENT_SECRET}
      - POSTGRES_URI_GATEWAY=${POSTGRES_URI_GATEWAY}
      - REDIS_URL_GATEWAY=${REDIS_URL_GATEWAY}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - gov-provider
      - gateway-postgres
      - gateway-redis
      - rabbitmq
    networks:
      - verifyme-network


networks:
  verifyme-network:
    driver: bridge

volumes:
  mongo-data:
  gov-postgres-data:
  gateway-postgres-data: